# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_date_time', models.DateTimeField(verbose_name='date published')),
                ('movie_director', models.CharField(max_length=200)),
                ('number_of_tickets', models.IntegerField()),
                ('movie_description', models.CharField(max_length=200)),
            ],
        ),
    ]
