# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='number_of_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
